polar:
  greeting: "The Configuration server welcomes you. Something changed"

server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

app:
  version: "catalog-api-v1"

spring:
  datasource:
    url: jdbc:postgresql://postgres/polar_bookstore
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://polar-keycloak/realms/PolarBookshop

management:
  endpoints.web.exposure.include: refresh, health, metrics, prometheus
  metrics.tag.application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      show-components: always
    probes:
      enabled: true
    group:
      readiness:
        include: readinessState,redis

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"


springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: jsl.group.catalog_service
  pathsToMatch: /**
  cache.disable: true

# TODO: security to be considered later
#  swagger-ui:
#    oauth2-redirect-uri: /swagger-ui/oauth2-redirect.html
#    oauth:
#      clientId:
#      clientSecret:
#      useBasicAuthenticationWithAccessCodeGrant: true