polar:
  greeting: "The Configuration server welcomes you. Something changed"

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

app:
  version: "api-v1"

spring:
  datasource:
    url: jdbc:postgresql://postgres/polar-bookstore
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  sql:
    init.mode: always
